project_id = "rvyoumuclbrjiaeurriy"

[functions.ai-assistant-webhook]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.elevenlabs-signed-url]
verify_jwt = false