project_id = "rvyoumuclbrjiaeurriy"

[functions.ai-assistant-webhook]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.elevenlabs-signed-url]
verify_jwt = false

[functions.predictive-analytics]
verify_jwt = true

[functions.create-tecnospeed-token]
verify_jwt = true

[functions.sync-bank-statement]
verify_jwt = true

[functions.categorize-transaction]
verify_jwt = false